export const GAME_CONFIG = {
  BONUS_AMOUNT: 10,
  BONUS_COOLDOWN_MS: 60000,
  QUICK_BET_AMOUNTS: [10, 50, 100, 500],
  MAX_USERNAME_LENGTH: 20,
  GAME_DURATION_MAX: 12,
};

export const LEADERBOARD_CONFIG = {
  TOP_PLAYERS_COUNT: 10,
  REFRESH_INTERVAL_MS: 30000,
};

export const SUPABASE_CONFIG = {
  SPINNER_COLOR: "#0013bcff",
  SPINNER_SIZE: 70,
};

export const PLINKO_BALL_CONFIG = {
  GRAVITY: 2800,
  AIR_DRAG: 0.992,
  RESTITUTION: 0.45,
  WALL_RESTITUTION: 0.55,
  BALL_RADIUS: 10,
  PIN_HIT_COOLDOWN: 70,
};

export const PLINKO_HISTORY_STORAGE_KEY = "plinko_history";
export const PLINKO_HISTORY_UPDATED_EVENT = "plinko_history_updated";

export const MAX_HISTORY_ITEMS = 100;
