export const GAME_CONFIG = {
  BONUS_AMOUNT: 10,
  BONUS_COOLDOWN_MS: 60000,
  QUICK_BET_AMOUNTS: [10, 50, 100, 500],
  MAX_USERNAME_LENGTH: 20,
  GAME_DURATION_MAX: 12,
};

export const LEADERBOARD_CONFIG = {
  TOP_PLAYERS_COUNT: 10,
  REFRESH_INTERVAL_MS: 30000,
};

export const SUPABASE_CONFIG = {
  SPINNER_COLOR: "#0013bcff",
  SPINNER_SIZE: 70,
};

export const PLINKO_BALL_CONFIG = {
  GRAVITY: 2800,
  AIR_DRAG: 0.992,
  RESTITUTION: 0.45,
  WALL_RESTITUTION: 0.55,
  BALL_RADIUS: 10,
  PIN_HIT_COOLDOWN: 70,
};

export const PLINKO_PHYSICS_CONFIG = {
  MIN_DIMENSION_PX: 1,
  MIN_PIN_RADIUS_PX: 4,
  SLOTS_Y_RATIO: 0.85,
  SLOTS_LEFT_RATIO: 0.06,
  SLOTS_RIGHT_RATIO: 0.94,
  START_X_BASE: 0.5,
  START_X_MIN: 0.05,
  START_X_MAX: 0.95,
  START_JITTER_STEP: 0.01,
  START_JITTER_MIN: -0.035,
  START_JITTER_MAX: 0.035,
  START_VX_SPREAD: 260,
  START_VX_JITTER_FACTOR: 1600,
  DT_MAX: 0.05,
  SUBSTEPS_PER_SECOND: 120,
  COLLISION_CULL_MULTIPLIER: 2.5,
  MIN_DIST_SQ: 0.0001,
  PENETRATION_SLOP: 0.5,
  TANGENTIAL_JITTER: 160,
  TANGENTIAL_JITTER_Y_FACTOR: 0.18,
  SLOT_T_MAX: 0.999999,
}

export const PLINKO_HISTORY_STORAGE_KEY = "plinko_history";
export const PLINKO_HISTORY_UPDATED_EVENT = "plinko_history_updated";

export const MAX_HISTORY_ITEMS = 100;
